version: '2'
services:
  db:
    container_name: ${CONTAINER_NAME}
    image: mysql
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - default

  
